shift Datomic and Neo4J out to profiles because they interfere with our Lucene:
ClassNotFoundException: org.apache.lucene.codecs.lucene50.Lucene50PostingsWriter